### ISSUE TITLE
MSP operator is not able to find the file backed store (aio) or block device when creating an MSP

### ISSUE THREAD

**Issue by hickersonj** [openebs/mayastor#1089]
**Describe the bug**
The MSP operator is not able to find a file backed store or formatted disk on the node. Using `disks: ["aio:///tmp/disk1.img"]` and/or `disks: ["/dev/sdz"]` results in a warning message `The block device(s): /dev/sdz can not be found` and stuck in creating for the MSP.

**To Reproduce**
```
cat <<EOF | kubectl create -f -
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: filepool-2
  namespace: mayastor
spec:
  node: endor
  disks: ["aio:///tmp/disk1.img"]
EOF
```

**Expected behavior**
The MSP will be created using either a file backed store or a block device.

** OS info (please complete the following information):**
- Distro: [Fedora 33]
- Kernel version - 5.12.9-200.fc33.x86_64
- MayaStor revision v1.0.0

**Additional context**
```
k describe mayastorpool filepool-2 -n mayastor
Name:         filepool-2
Namespace:    mayastor
Labels:       <none>
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         MayastorPool
Metadata:
  Creation Timestamp:  2022-02-07T22:47:15Z
  Finalizers:
    io.mayastor.pool/cleanup
  Generation:  1
  Managed Fields:
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:disks:
        f:node:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-07T22:47:15Z
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:available:
        f:capacity:
        f:state:
        f:used:
    Manager:      Mayastor pool operator
    Operation:    Update
    Time:         2022-02-07T22:47:16Z
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"io.mayastor.pool/cleanup":
    Manager:         unknown
    Operation:       Update
    Time:            2022-02-07T22:47:16Z
  Resource Version:  4045401
  UID:               abed04b8-302f-492f-9465-2a47974870f3
Spec:
  Disks:
    aio:///tmp/disk1.img
  Node:  endor
Status:
  Available:  0
  Capacity:   0
  State:      Creating
  Used:       0
Events:
  Type  Reason   Age   From          Message
  ----  ------   ----  ----          -------
  Warn  Missing  72s   msp-operator  The block device(s): aio:///tmp/disk1.img can not be found
  Warn  Missing  71s   msp-operator  The block device(s): aio:///tmp/disk1.img can not be found
```

**Comment by tiagolobocastro** [comment]
@hickersonj did you create the file /tmp/disk1.img on the mayastor node?
Does `/dev/sdz` have any filesystem on it?

**Comment by hickersonj** [comment]
Yes they were created on the mayastor nodes.  And `/dev/sdz`  has an ext4 filesystem.

**Comment by tiagolobocastro** [comment]
IIRC we report devices with filesystem as "used", so we won't make use them for pools. Could you try to remove the filesystem and retry?

**Comment by hickersonj** [comment]
Removed the filesystem, same issue claims `/dev/sdz can not be found`. It's an odd error, unless perhaps the pod cannot reach the hosts devices or file system? Is there a way to debug that?  Thanks!

**Comment by tiagolobocastro** [comment]
Would you be able to curl the the block devices from the node, eg:
curl "http://ANY_NODE_IP:30011/v0/nodes/NODE_NAME/block_devices?all=true"

**Comment by hickersonj** [comment]
@tiagolobocastro thanks, that helped, the /dev/sdz wasn't attached to a loopback filesystem (it's a virtual disk), once I attached it the msp operator detected it.  However, aio is still not working.

**Comment by adamcharnock** [comment]
I'm getting setup with Mayastor now too, and I am having the same issue with a file-based disk not mounting.

```yaml
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: "NODENAME-pool1"
  namespace: mayastor
spec:
  node: "NODENAME"
  disks: ["aio:///var/openebs/mayastor/images/disk1.img?blk_size=4096"]
```

I've updated both the `mayastor` and `mayastor-csi` daemonsets to mount in the `/var/openebs` directory from the host. I'm creating the files as follows:

    truncate --size=200G /var/openebs/mayastor/images/disk1.img

I see the error on the MSP as follows:

```
│   Warn   Missing   15m    msp-operator  The block device(s): aio:///var/openebs/mayastor/images/disk1.img │
│ ?blk_size=4096 can not be found                                                                           │
│   Warn   Missing   10m    msp-operator  The block device(s): aio:///var/openebs/mayastor/images/disk1.img │
│ ?blk_size=4096 can not be found                                                                           │
│   Error  Creating  2m13s  msp-operator  Retry attempts (10) exceeded                                      │
```

@hickersonj – I don't suppose you've figured this out in the last 24 hours?

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro thanks, that helped, the /dev/sdz wasn't attached to a loopback filesystem (it's a virtual disk), once I attached it the msp operator detected it. However, aio is still not working.

Did you map the host /tmp into the mayastor container?

**Comment by tiagolobocastro** [comment]
@adamcharnock , same thing is that mapped into the mayastor container? Also please note the file is not going to be reported from the block_devices api as it's just a file (useful for testing purposes only).

**Comment by adamcharnock** [comment]
Thank you for the reply!

> same thing is that mapped into the mayastor container? 

Certainly seems so. Shell from inside one of the mayastor containers:

<img width="768" alt="Screenshot 2022-02-16 at 13 47 34" src="https://user-images.githubusercontent.com/138215/154277720-7e99baf7-26ab-4e00-8625-d0c2731c3c32.png">

> Also please note the file is not going to be reported from the block_devices api as it's just a file

Yeah, I suspected as much. Figured I just show as much as possible.

> (useful for testing purposes only).

This I was actually wondering about. Do you say this due to performance reasons, or due of reliability reasons? I was hoping to make small-scale use of an image-backed pool until I could justify adding extra physical disks to the nodes.

I could also spin up a virtual disk (like @tiagolobocastro), but was going to keep things simple with a file-based-disk if I could.

**Comment by hickersonj** [comment]
> > @tiagolobocastro thanks, that helped, the /dev/sdz wasn't attached to a loopback filesystem (it's a virtual disk), once I attached it the msp operator detected it. However, aio is still not working.
> 
> Did you map the host /tmp into the mayastor container?

I'm not sure how to do that. I was thinking perhaps the pod just couldn't find the file outside of the container.  So I tried to put it in /var/lib/mayastor/tmp but it still didn't work.  If you have a method to expose the file I'll update.

**Comment by tiagolobocastro** [comment]
@adamcharnock, sorry for testing I actually considering mostly the file in /tmp. If you've got an image on fast storage that's not temporary I guess that's an option, though I'd have to double check that. (But please note we don't support any image format, we use files as if they were a "raw" block device).

So turns out we can't actually use file-based pools through the msp operator at the moment as the operator only supports block devices. 
You can manually create a pool, example:
```
curl -X PUT http://192.168.122.154:30011/v0/nodes/ksnode-3/pools/pool-1 -d "{\"disks\": [\"aio:///tmp/disk1.img\"], \"labels\": {\"openebs.io/created-by\": \"msp-operator\"}}" -H "Content-Type: application/json"
```
However, please note it will not show up as an msp CRD (it will show up when using the kubectl mayastor plugin)
To delete the pool:
```
curl -X DELETE http://192.168.122.154:30011/v0/nodes/ksnode-3/pools/pool-1
```

**Comment by adamcharnock** [comment]
Thank you for looking into it @tiagolobocastro!

I've just put together that uses a loopback device as per @hickersonj suggest, and in that case the storage pools immediately came online.

For anyone trying this too, the process looks something like this:

```yaml
# Create file
dd if=/dev/zero of=/var/openebs/mayastor/images/disk1.img bs=4M count={{ disk_gb/4)* 1024 }}

# Create partition scheme (g, n, accept defaults, w)
sudo fdisk /var/openebs/mayastor/images/disk1.img

# Setup the loop device (and set this to run on startup somehow, TBA)
losetup /dev/loop0 /var/openebs/mayastor/images/disk1.img
```

Then your mayastor pools look like this:

```
apiVersion: openebs.io/v1alpha1
kind: MayastorPool
metadata:
  name: worker1-pool1
  namespace: mayastor
spec:
  disks: ["/dev/loop0"]
  node: worker1
```yaml

**Comment by GlennBullingham** [comment]
Adding the suggestion of @hickersonj and @adamcharnock as a workaround for this known issue to the V1.0.1 patch release notes.

The validation problem in the operator which has been identified will be addressed in a future release forward of V1.0.1

**Comment by abhisheksinghbaghel** [comment]
I am trying what @adamcharnock suggested above and keep running in to below, any suggestions?

```

  Mar 29 08:07:15.191  WARN msp_operator: HTTP response error: error in response: status code '400 Bad Request', content: 'RestJsonError { details: "create_pool::status: InvalidArgument, message: \"failed to import pool aks-agentpool-11644018-vmss000000\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Tue, 29 Mar 2022 08:07:15 GMT\"} }", kind: InvalidArgument }', retry scheduled @Tue, 29 Mar 2022 08:07:20 +0000 (5 seconds from now)
    at control-plane/msp-operator/src/main.rs:828
    in kube_runtime::controller::reconciling object with object.ref: MayastorPool.v1alpha1.openebs.io/aks-agentpool-11644018-vmss000000.mayastor, object.reason: error policy requested retry

```

**Comment by paulyoong** [comment]
Hi @abhisheksinghbaghel. The typical scenario we have seen where this has occurred is when a disk which has been used in a previous pool is attempting to be reused in a new pool with a different name. When a disks gets added to a pool there is some metadata written to it which includes the pool name. The `InvalidArgument` error gets returned because the names of the old pool and new pool do not match.

The solution to this has been to erase the metadata from the disk. You could use `dd` to erase the first 16MiB of the disk and then try to recreate the pool.

**Comment by abhisheksinghbaghel** [comment]
@paulyoong thank you for your response. I see this happening for freshly created disks as well.
Unfortunately, I can't see anything in the mayastor daemon logs to suggest what could have been happening. Any pointers on where can I find relevant logs to tell me why the failure happened?

**Comment by paulyoong** [comment]
@abhisheksinghbaghel I think this is an area where we could improve with our error reporting to make it more obvious what is going on. 

This is the code where we try to create/import pools - https://github.com/openebs/mayastor/blob/0527045052907bb3e560f4fef10f09ed2078ca0f/mayastor/src/lvs/lvs_pool.rs#L293. Typically in the logs we would look for something like "failed to import pool" but you already provided this and it was lacking details.

I haven't previously seen this issue with freshly created disks, so that is interesting. I will see if I can reproduce this issue and will post any relevant information if I find it.

**Comment by GlennBullingham** [comment]
@pawanpraka1 _is_ this issue being addressed for 3.3 (i.e. Mayastor 2.0)?  I'm not aware of any work in progress to that effect.

**Comment by pawanpraka1** [comment]
@GlennBullingham this was the backlog (todo) item in 3.3 and we did not get any resource to work on it.

**Comment by wibed** [comment]
has this been resolved or is it in the works?

**Comment by tiagolobocastro** [comment]
Yes this is working, example:

```
> ssh 10.0.0.114 sudo fallocate -l 200MiB /var/local/io-engine/disk.img
> NODE=ksnode-2 DISK=aio:///var/local/io-engine/disk.img NAMESPACE=mayastor envsubst < ~/git/kube-helper/storage-pool.yaml | kubectl create -f -
> kubectl -n mayastor get dsp
```

Note: There's currently a bug where we set the bdev UUID to 0 for these files, though shouldn't have any real impact though as the pool uuid itself is auto-generated and not 0, more of an annoyance if you use cli to list.. I'll get this fixed too.

**Comment by adamcharnock** [comment]
I'm back! After much doubt and cursing, I can also confirm that this is now working. 

For anyone else coming across this: For a while I had the exact same problem still, and if I checked the `mayastor-io-engine` logs I could see reports of `ENOSPC No space left on device`, which seemed to appear against the `DiskPool` as the `... can not be found` error.

In my case I was messing up how I was `fdisk`ing the files. I'll leave some ansible tasks here in case it helps anyone:
 
**Edited**: Now uses `fallocate` as per @tiagolobocastro's suggestion below

```yaml
- name: Create mayastor disk image
  tags: [ 'k8s_app_mayastor' ]
  notify: partition-disk
  command:
    creates: "{{ disk_file }}"
    # We add an extra 4M at the end just to keep everything happy
    # (otherwise we seem to get issues when fdisking the file)
    cmd: "fallocate -l {{ (size_gb|int * 1024) + 4 }}MiB {{ disk_file }}"
    # EDITED. Command was previously this:
    # cmd: "dd if=/dev/zero of={{ disk_file }} bs=4M count={{ ((size_gb|int)/4 * 1024)|round(0, 'ceil')|int + 1 }}"

# Handlers

- name: Setup disk partition
  listen: partition-disk
  tags: [ 'k8s_app_mayastor' ]
  vars:
    sector_size: 512
    size: "{{ (size_gb|int) * 1024 * 1024 * 1024 / sector_size }}"
  command:
    cmd: sfdisk {{ disk_file }}
    stdin: |
      label: gpt
      label-id: 10000000-0000-4000-{{ "%04d" | format(host_number|int) }}-{{ "%012d" | format(disk_number|int) }}
      device: {{ disk_file }}
      unit: sectors
      first-lba: 2048
      last-lba: {{ size|int - 1 }}
      
      {{ disk_file }}1 : start=        2048, size=   {{ size|int - 2048 }}

```
