### ISSUE TITLE
use a new mayastor operator to make the disc additions based on the cloud commands 

### ISSUE THREAD

**Issue by alokhom** [openebs/mayastor#1123]
**Is your feature request related to a problem? Please describe.**
yes. the discs need to be added manually and attached  on nodes for the mayastor deployment.

**Describe the solution you'd like**
I need a mayastor operator to use the cloud commands like gcloud or az CLI from a container to attach disks to k8s worker VMs (mayastor worker nodes)  using extra definition from the MayastorPool manifests like disc size, type( SSD, nvme), zone, projectName and resourceName.  

**Describe alternatives you've considered**
As on date, I have manually added the discs to mayasotr worker nodes using the cloud documentation. Most workplaces will not allow to touch k8s nodes but are OK using operators ( helm charts , infra as code) to deploy the discs or infra changes. So one such change for mayastor to work is an operator needed to add the disks to the relevant nodes with zone, disc type, disc size, projectname and resourcename. It must also auto-detect and populate the disks KV in the mayastor pool manifest. As of now we manually do the disk attach and populate the node and the disks KV in the MayastorPool manifest. 

**Additional context**
If we look at the below manifest, we have only node and disks info but we have to manually attach it and populate to deploy this manifest. Instead, we can modify with another field like discSize, numberOfDisk, discType, projectname or resourcename to automate and make the discs in the background, attach it, and autopopulate discs KV for the MayastorPool CR. For gke worker nodes it needs gcloud commands [link ](https://cloud.google.com/compute/docs/disks/add-persistent-disk)or a gcloud [docker ](https://hub.docker.com/r/google/cloud-sdk/) to attach disk by running the relevant gcloud disk commands. The same can be done using az command or aws-cli commands for its cloud. 
```
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: pool-on-node-1
  namespace: mayastor
spec:
  node: workernode-1-hostname
  disks: ["/dev/sdx"]`
```

change needed:
```
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: pool-on-node-1
  namespace: mayastor
spec:
  node: workernode-1-hostname
  diskSize: 1T
  numberOfDisk: 3
  discType: [ "ssd","NVMe" ]
  projectName:  gcloud-projectID (for gke ) 
  resourceName: <aks-resource name> (for azure ) 
```

references: 
for azure the commands to attach disk to mayastoer worker node VMs are mentioned in this [link ](https://github.com/kellyhair/mayastor-terraform-playground/tree/main/azure-aks)
