### ISSUE TITLE
support default storageclass

### ISSUE THREAD

**Issue by weironz** [openebs/mayastor#1487]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
support config default storageclass in helm charts
```
root@node33:~# kubectl get sc
NAME                      PROVISIONER               RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
mayastor-single-replica (default)   io.openebs.csi-mayastor   Delete          Immediate              false                  16m
```

**Describe alternatives you've considered**

**Additional context**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-single-replica
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.persistence.defaultClass | quote }}
parameters:
  repl: '1'
  protocol: 'nvmf'
  ioTimeout: '60'
provisioner: io.openebs.csi-mayastor

```
