### ISSUE TITLE
poor performance and mayastor-io-engine consumes only 2 cores

### ISSUE THREAD

**Issue by aep** [openebs/mayastor#1522]
testing a 2 replica volume, performance is unexpected with roughly 3K IOPS
the underlying nvmes have one million IOPS and this is over 200GBit mellanox ethernet with roughly 0.1 ms latency.
kernel nvme-of  can saturate the link at 20GB/s while maya doesnt even reach 200MB/s

i noticed that the mayastor-io-engine process is spawning a single tokio worker according to the log.
I'm not super familiar with tokio but this sounds low? a single threaded IO thread would not be able to reach a million IOPS simply because the cpu isnt that fast.

```
  2023-10-12T10:54:43.007538Z  INFO actix_server::builder: starting 1 workers
    at /build/cargo-vendor-dir/actix-server-2.2.0/src/builder.rs:200

  2023-10-12T10:54:43.007564Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
    at /build/cargo-vendor-dir/actix-server-2.2.0/src/server.rs:197
```

according to htop, mayastor-io-engine has two threads, each at 100% even while idle. i'm assuming this is due to SPDK polling in a busy loop, so its expected.  But the cpu usage doesnt go up with load, its just constant. i would have expected non SPDK things to go in a different thread?

**Comment by tiagolobocastro** [comment]
Are you binding to the correct network? You can check this by inspecting the `status.attachmentMetadata.uri` from the `volumeattachment`.
That is the server for the rest interface, it's not used by the IO path.
Depending on how you are testing you might want to add more parallel jobs from the initiator side.
As you've pointed out we're polling so the cpu usage will remain high, that's expected at the moment. Have you isolated the mayastor cores as well?

**Comment by aep** [comment]
the uri is a bit confusing because it just shows one target although this is a replica-2

the IP shown there just seems to be the host where the pod is running

```
root@benchr:~# kubectl describe volumeattachment
Name:         csi-f8b704573038afd0f5b0d7086ae9ff48a3be4aaee55bc97b57b1f9136228f290
Namespace:    
Labels:       <none>
Annotations:  csi.alpha.kubernetes.io/node-id: benchr
API Version:  storage.k8s.io/v1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:  2023-10-15T12:48:50Z
  Finalizers:
    external-attacher/io-openebs-csi-mayastor
  Resource Version:  35362
  UID:               6086fa3a-4dcf-4fea-8781-0d615015ad44
Spec:
  Attacher:   io.openebs.csi-mayastor
  Node Name:  benchr
  Source:
    Persistent Volume Name:  pvc-391aa8e9-bde9-4aa3-b85f-eaf6e1e82a2f
Status:
  Attached:  true
  Attachment Metadata:
    Io Timeout:  30
    Uri:         nvmf://192.168.56.3:8420/nqn.2019-05.io.openebs:391aa8e9-bde9-4aa3-b85f-eaf6e1e82a2f?hostnqn=nqn.2019-05.io.openebs:node-name:benchr
Events:          <none>

```

the mayastor cli appears to be more useful.
the outpool looks correct.

```
root@benchr:/tmp# kubectl-mayastor get volumes -o yaml
- spec:
    num_replicas: 2
    size: 10737418240
    status: Created
    target:
      node: benchr
      protocol: nvmf
    uuid: 391aa8e9-bde9-4aa3-b85f-eaf6e1e82a2f
    topology:
      pool_topology: !labelled
        exclusion: {}
        inclusion:
          openebs.io/created-by: operator-diskpool
    policy:
      self_heal: true
    thin: false
    num_snapshots: 0
  state:
    target:
      children:
      - state: Online
        uri: bdev:///d3c1865a-6ecf-4979-bc52-67097cfbcc89?uuid=d3c1865a-6ecf-4979-bc52-67097cfbcc89
      - state: Online
        uri: nvmf://192.168.56.2:8420/nqn.2019-05.io.openebs:e7a2db2c-158a-4925-8c5c-e1bd991e6016?uuid=e7a2db2c-158a-4925-8c5c-e1bd991e6016

```

i also rebuilt the test system from scratch to make sure __all__  IP traffic is on the mellanox network.

**Comment by aep** [comment]
ok i'm super confused.

1. created a StorageClass with repelica: 1
2. created a pvc and a pod
3. observed where the pod was created, then deleted the pod and recreated it with nodeselector on a _different_ node without touching the pvc
4. now i get 300K iops read, 160k write, which is about 30% of native, but we're probably network bound now.


```
kubectl-mayastor get volumes -o yaml
- spec:
    num_replicas: 1
    size: 10737418240
    status: Created
    target:
      node: benchr
      protocol: nvmf
    uuid: 7de16c85-ed4b-4d72-a485-948d9814d0fe
    topology:
      pool_topology: !labelled
        exclusion: {}
        inclusion:
          openebs.io/created-by: operator-diskpool
    policy:
      self_heal: true
    thin: false
    num_snapshots: 0
  state:
    target:
      children:
      - state: Online
        uri: bdev:///d53cd54b-ca53-4826-85f8-888670685f5b?uuid=d53cd54b-ca53-4826-85f8-888670685f5b
      deviceUri: nvmf://192.168.56.3:8420/nqn.2019-05.io.openebs:7de16c85-ed4b-4d72-a485-948d9814d0fe?hostnqn=nqn.2019-05.io.openebs:node-name:benchl
      node: benchr
      rebuilds: 0
      protocol: nvmf
      size: 10737418240
      state: Online
      uuid: 2d006470-a1b0-4748-97e5-c1a0ee6b5650
    size: 10737418240
    status: Online
    uuid: 7de16c85-ed4b-4d72-a485-948d9814d0fe
    replica_topology:
      d53cd54b-ca53-4826-85f8-888670685f5b:
        node: benchr
        pool: benchr2
        state: Online
        child-status: Online
        usage:
          capacity: 10737418240
          allocated: 10737418240
          allocated_snapshots: 0
          allocated_all_snapshots: 0
    usage:
      capacity: 10737418240
      allocated: 10737418240
      allocated_replica: 10737418240
      allocated_snapshots: 0
      allocated_all_snapshots: 0
      total_allocated: 10737418240
      total_allocated_replicas: 10737418240
      total_allocated_snapshots: 0

````

this looks like its on node benchr, but the pod is on benchl

```
root@benchr:/tmp# kubectl describe pods
Name:             fio
Namespace:        default
Priority:         0
Service Account:  default
Node:             benchl/192.168.56.2
Start Time:       Sun, 15 Oct 2023 15:28:49 +0200
Labels:           app=fio
Annotations:      <none>
Status:           Running
IP:               10.0.1.59
IPs:
  IP:  10.0.1.59
Containers:
  fio:
    Container ID:  cri-o://9cf98b5164229029e03562bcd70558adf118f2e152d1863059cb52ced596231d
    Image:         mayadata/fio
    Image ID:      docker.io/mayadata/fio@sha256:05ed68f71aa7f8d713b440befa645758b6fc609a18e3264aaa93a70864c3faee
    Port:          <none>
    Host Port:     <none>
    Args:
      sleep
      1000000
    State:          Running
      Started:      Sun, 15 Oct 2023 15:28:56 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w7vq9 (ro)
    Devices:
      /dev/xvda from ms-volume
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  ms-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-1
    ReadOnly:   false
  kube-api-access-w7vq9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/hostname=benchl
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s

````





300K iops also appears to be the _total_ IOPS of a node, even when the volumes are on different pools. 
i'm still super confused how this all works. I guess this is because there's two thread spinning and all IO goes through that anyway?

Can i really not increase the thread count?
