### ISSUE TITLE
ReadWriteMany support

### ISSUE THREAD

**Issue by MrMarble** [openebs/mayastor#1567]
Issue #1127 was closed as completed but trying to create a PVC with RWX access mode
throws an error: `failed to provision volume with StorageClass "mayastor-thin": rpc error: code = InvalidArgument desc = Invalid volume access mode: 5`

Is this not supported?

PVC manifest
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-thin
```

StorageClass manifest
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-thin
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  ioTimeout: "60"
  protocol: nvmf
  repl: "1"
  thin: "true"
provisioner: io.openebs.csi-mayastor
```
