### ISSUE TITLE
Prometheus exporter incorrectly reports latency?

### ISSUE THREAD

**Issue by adamcharnock** [openebs/mayastor#1690]
**Describe the bug**

The prometheus exporter is reporting very high values for:

* `replica_write_latency_us`
* `replica_read_latency_us`
* `volume_write_latency_us`
* `volume_read_latency_us`

For my larger volumes (100G-200G) I'm seeing values in the 10M - 100M range. Which would imply latencies of 10-100 seconds, which I am quite sure isn't actually the case. Even the saner numbers I am seeing are in the 10k-100k range, which is still in the 0.01-0.1 second region.

**To Reproduce**

* Example output from the `metrics-exporter-io-engine` service.

**Expected behavior**

I would expect these numbers to be smaller by a factor of around 100k.

**Screenshots**

The results I am seeing:

<img width="1080" alt="Screenshot 2024-07-13 at 17 41 01" src="https://github.com/user-attachments/assets/4a8efa16-8394-414d-bdb4-e8c742f9cb31">

Result of `fio` test:

<img width="1919" alt="Screenshot 2024-07-13 at 17 21 08" src="https://github.com/user-attachments/assets/2292f895-d4ac-4f2c-bc2d-d5ada712ee7d">

Result of `ioping`:

<img width="736" alt="Screenshot 2024-07-13 at 17 18 08" src="https://github.com/user-attachments/assets/2267da46-bf27-4375-8784-0f715b4eb089">

** OS info (please complete the following information):**
 - Distro: Ubuntu 22.04
 - Kernel version: `5.15.0-113`
 - MayaStor revision: `docker.io/openebs/mayastor-io-engine:v2.6.1`

**Comment by tiagolobocastro** [comment]
I believe this is happening because the counters are actually the total latency.
@abhilashshetty04 could you please confirm and suggest how to use these counters?

**Comment by adamcharnock** [comment]
Ah ok. So, testing this, when I run:

```
rate(replica_read_latency_us{pv_name="pvc-4e02bd25-b6d3-490f-a05e-d30531931e89"}[10m])
```

I see something like this (lines are each different servers):

<img width="1601" alt="Screenshot 2024-07-16 at 10 48 48" src="https://github.com/user-attachments/assets/69ee204f-f066-4a26-bd08-4a2e124312a7">

This is showing the rate of increase in `us` per second. While this does look a lot more sensible, **can someone confirm this is the correct way to interpret this?** Values are mostly in the 0-20 range.

**Comment by abhilashshetty04** [comment]
Hi @adamcharnock, `replica_write_latency_us` is sum of all write io latency on the specific replica. For getting `avg_latency` over a timestamp probably we should do this

(irate(replica_read_latency_us{name="<replica_name>"}[1m]))/(irate(replica_num_read_ops{name="<replica_name>"}[1m]))

We consider number of operations in the time period as well.

**Comment by abhilashshetty04** [comment]
> Ah ok. So, testing this, when I run:
> 
> ```
> rate(replica_read_latency_us{pv_name="pvc-4e02bd25-b6d3-490f-a05e-d30531931e89"}[10m])
> ```
> 
> I see something like this (lines are each different servers):
> 
> <img alt="Screenshot 2024-07-16 at 10 48 48" width="1601" src="https://private-user-images.githubusercontent.com/138215/349033496-69ee204f-f066-4a26-bd08-4a2e124312a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjQwMTUsIm5iZiI6MTcyMTEyMzcxNSwicGF0aCI6Ii8xMzgyMTUvMzQ5MDMzNDk2LTY5ZWUyMDRmLWYwNjYtNGEyNi1iZDA4LTRhMmUxMjQzMTJhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTU1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjVmMjhmM2YzNTQ2ZmM0OTUyMmFmMGE0YTAxYzI3M2MwMTcxN2ZjNjIxODI1MTQ1MjkxZWMyMzg5YjYwNGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ze_V8sUxYPgGCuiSiYIrfVL2HyktLuNmd0SrtAu8gSw">
> This is showing the rate of increase in `us` per second. While this does look a lot more sensible, **can someone confirm this is the correct way to interpret this?** Values are mostly in the 0-20 range.

Are you filtering for 2 replicas here? Can you share the full screenshot?

**Comment by adamcharnock** [comment]
Thank you @abhilashshetty04. I see now. So these metrics are total latency, and the total is added to per-operation. We therefore divide by the number of ops to get the average latency.

So, using your example:

Note: I use `rate()` here as it looks better for the purposes of charting (likely because I have a low amount of disk traffic on this cluster, causing `irate` to show discontinuous lines

```
(
    (rate(replica_read_latency_us[10m]))
    /
    (rate(replica_num_read_ops[10m]))
) > 200
```

Gives:

<img width="1193" alt="Screenshot 2024-07-17 at 12 02 50" src="https://github.com/user-attachments/assets/95077f11-bfa0-48d1-b345-0235f618dfa6">

So I can see 4 replicas that have latencies over 200us (over the last 1h). (Note that this cluster is connected via a dedicated 10g hardware switch, all servers are in the same rack)

Followup question: Do you have a ballpark feel for what kind of latency is acceptable?

Thank you for the help!

**Comment by abhilashshetty04** [comment]
@adamcharnock , Since you are visualising `replica` stats. It would not involve any network hops. Are your backend disks for pool local to the node?

Can you try to plot the graph using `irate` with 10m. Wanted to check how does time axis change with that.

**Comment by adamcharnock** [comment]
Certainly @abhilashshetty04. 

# Using `rate` (old version)

```
(
    (rate(replica_read_latency_us[10m]))
    /
    (rate(replica_num_read_ops[10m]))
)
```

Produces:

<img width="1355" alt="Screenshot 2024-07-18 at 10 12 23" src="https://github.com/user-attachments/assets/789e8ffc-0e21-4b04-852a-270be9565d3e">


# Using `irate` (as requested)

```
(
    (irate(replica_read_latency_us[10m]))
    /
    (irate(replica_num_read_ops[10m]))
)
```

Produces:

<img width="1351" alt="Screenshot 2024-07-18 at 10 08 30" src="https://github.com/user-attachments/assets/307336dc-6a0a-46f8-9016-2dcd83118b0c">

---

In both charts the two continuous purple lines are replicas of the same volume. I think this volume has fairly consistent writes, and I assume that is why we have continuous data for it.

**Comment by adamcharnock** [comment]
> Since you are visualising replica stats. It would not involve any network hops. Are your backend disks for pool local to the node?

I have three nodes in the cluster, each of which run mayastor. The majority of volumes have replicas. My assumption was therefore that some replicas would have low latency due to being local, and some replicas would have higher latency due to being on a remote mayastor node. But perhaps I have misunderstood something?

**Comment by abhilashshetty04** [comment]
@adamcharnock , writes go to to all the replicas in sync manner from volume target. However, reads are round robin to the replicas.  `latency` depends on backing device of the pool. Incase you have similar device for all replicas then you may see similar numbers.

**Comment by abhilashshetty04** [comment]
> olumes have replicas.

`replica_stats` are from replica layer. Here, it doesnt matter if its remote or local to the target. For the remote replica also when the IO is received it caculates latency from the time it dispatches IO downward to the pool. Network hop latency is added in `volume_read_latency_us` and `volume_write_latency_us` This metrics is for volume target resource.

**Comment by tiagolobocastro** [comment]
> some replicas would have low latency due to being local, and some replicas would have higher latency due to being on a remote mayastor node. But perhaps I have misunderstood something?

No you did not. The nuance here is that the per-replica latency which we are exporting is at their pool level - so below any network hop takes place.
The volume latency does indeed take this into account, but here we don't have per-replica latency, it's kinda the average of all replicas. 
We could potentially expose per-replica latency at the volume level, but that's not currently in scope.

Maybe this diagram helps a bit, pardon my lack of artistic gifts :D 

```ascii                                                                             
                                         │                │                    
                           │             │                │                    
           Node 1          │   Node 2    │    Node 3      │                    
                           │             │                │                    
                           │             │                │                    
                           │             │                │                    
                           │             │                │                    
                           │             │                │                    
                           │             │                │                    
                           │  ┌────────┐ │                │                    
   Network│                │  │ Volume ├─┼─────┐          │          │  Volume 
          │         ┌──────┼──┤        │ │     │          │          │         
  Latency │         │      │  └───┬────┘ │     │          │          │ Latency 
          │         │      │      │      │     │          │          │         
          │         │      │      │      │     │          │          │         
          ▼         │      │      │      │     │          │          │         
                    ▼      │      ▼      │     ▼          │          │         
          │       ┌───┐    │   ┌───┐     │  ┌───┐         │          │         
          │       │R1 │    │   │R2 │     │  │R3 │         │          │         
  Replica │       └───┘    │   └───┘     │  └───┘         │          │         
          │                │             │                │          │         
  Latency │      ┌──────┐  │  ┌───────┐  │  ┌──────┐      │          │         
          │      │      │  │  │       │  │  │      │      │          │         
          │      │ Disk │  │  │  Disk │  │  │ Disk │      │          │         
          ▼      │      │  │  │       │  │  │      │      │          ▼         
                 └──────┘  │  └───────┘  │  └──────┘      │                    
                           │             │                │                    
                           │             │                │                    
                           │             │                │                    
```

**Comment by adamcharnock** [comment]
Thank you @tiagolobocastro and @abhilashshetty04, this has been really very useful. Also, `irate` started the behave normally when I dropped the sampling rate for the service down to 5m (from 30s), as [per the docs](https://openebs.io/docs/user-guides/replicated-storage-user-guide/replicated-pv-mayastor/advanced-operations/monitoring).

If it helps anyone, here is `PrometheusRule` for our mayastor installation (critique welcome):

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: mayastor-rules
  namespace: monitoring-system
spec:
  groups:
    - name: mayastor-alerts
      rules:
      - alert: MayastorDiskPoolReadLatencyHigh
        expr: irate(diskpool_read_latency_us[10m]) / irate(diskpool_num_read_ops[10m]) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High read latency on disk pool"
          description: "The read latency on disk pool {{ $labels.name }} on node {{ $labels.node }} is higher than 1ms."

      - alert: MayastorDiskPoolWriteLatencyHigh
        expr: irate(diskpool_write_latency_us[10m]) / irate(diskpool_num_write_ops[10m]) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High write latency on disk pool"
          description: "The write latency on disk pool {{ $labels.name }} on node {{ $labels.node }} is higher than 1ms."

      - alert: MayastorDiskPoolUsageHigh
        expr: max by (name) (diskpool_used_size_bytes) / max by (name) (diskpool_total_size_bytes) > 0.75
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High disk pool usage"
          description: "The disk pool {{ $labels.name }} is using more than 75% of its capacity."

      - alert: MayastorDiskPoolUsageCritical
        expr: max by (name) (diskpool_used_size_bytes) / max by (name) (diskpool_total_size_bytes) > 0.90
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Critical disk pool usage"
          description: "The disk pool {{ $labels.name }} is using more than 90% of its capacity."

      - alert: MayastorDiskPoolStatusDown
        expr: diskpool_status == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk pool is down"
          description: "The disk pool {{ $labels.name }} on node {{ $labels.node }} is down."

      - alert: MayastorReplicaReadLatencyHigh
        expr: (irate(replica_read_latency_us[10m])) / (irate(replica_num_read_ops[10m])) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High read latency on replica"
          description: "The read latency on replica {{ $labels.pv_name }} on node {{ $labels.node }} is higher than 1ms."

      - alert: MayastorReplicaWriteLatencyHigh
        expr: (irate(replica_write_latency_us[10m])) / (irate(replica_num_write_ops[10m])) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High write latency on replica"
          description: "The write latency on replica {{ $labels.pv_name }} on node {{ $labels.node }} is higher than 1ms."

      - alert: MayastorReplicaReadOpsHigh
        expr: sum by (pv_name) (irate(replica_num_read_ops[10m])) > 5000
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High number of read operations on replica"
          description: "The number of read operations on PV {{ $labels.pv_name }} is higher than 5000 per second for 15 minutes."

      - alert: MayastorReplicaWriteOpsHigh
        expr: sum by (pv_name) (irate(replica_num_write_ops[10m])) > 5000
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High number of write operations on replica"
          description: "The number of write operations on PV {{ $labels.pv_name }} is higher than 5000 per second for 15 minutes."

      # Volume latency includes network latency
      - alert: MayastorVolumeReadLatencyHigh
        expr: (irate(volume_read_latency_us[10m])) / (irate(volume_num_read_ops[10m])) > 3000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High read latency on volume"
          description: "The read latency on volume {{ $labels.pv_name }} on node {{ $labels.node }} is higher than 3ms"

      # Volume latency includes network latency
      - alert: MayastorVolumeWriteLatencyHigh
        expr: (irate(volume_write_latency_us[10m])) / (irate(volume_num_write_ops[10m])) > 3000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High write latency on volume"
          description: "The write latency on volume {{ $labels.pv_name }} on node {{ $labels.node }} is higher than 3ms"

      - alert: MayastorVolumeReadOpsHigh
        expr: sum by (pv_name) (irate(volume_num_read_ops[10m])) > 5000
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High number of read operations on volume"
          description: "The number of read operations on PV {{ $labels.pv_name }} is higher than 5000 per second for 15 minutes."

      - alert: MayastorVolumeWriteOpsHigh
        expr: sum by (pv_name) (irate(volume_num_write_ops[10m])) > 5000
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High number of write operations on volume"
          description: "The number of write operations on PV {{ $labels.pv_name }} is higher than 5000 per second for 15 minutes."
```

Also the `ServiceMonitor`:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mayastor
  name: mayastor
  namespace: openebs-system
spec:
  endpoints:
    # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint
  - honorLabels: true
    port: metrics
    interval: 5m
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: metrics-exporter-io-engine
```
