### ISSUE TITLE
[Doc Source]: [how to use before device]

### ISSUE THREAD

**Issue by MABIY** [openebs/mayastor#1695]
**new content**
l want to access data from mayastor before use device.
but find [doc](https://mayastor.gitbook.io/introduction/troubleshooting/faqs): 
**Since the replicas (data copies) of Mayastor volumes are held entirely within Blobstores, it is not possible to directly access the data held on pool's block devices from outside of Mayastor**
so how to use before device.
blows is current pool.
```yaml
apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: mayastor
spec:
  node: "node1"
  disks: [ "/dev/disk/by-path/acpi-VMBUS:01-vmbus-00000000000188990000000000000000-lun-0" ]
```
only replace disks to old device?
