### ISSUE TITLE
Dynamic creation of disk pools

### ISSUE THREAD

**Issue by metsuke0** [openebs/mayastor#1707]
**Is your feature request related to a problem? Please describe.**
I autoscale my EC2 nodes and I need disk pools on every node with a certain label.

**Describe the solution you'd like**
Given certain topology/label constraints, a disk pool can be allocated to a node upon startup. 

If a node is terminated or stopped, the disk pool would remain, along with its PVs and PVCs. When a new node is created, the disk pool would be assigned to that node along with the PVs and PVCs.

**Describe alternatives you've considered**
Portworx does this. Their StorageCluster kind is a good example of it working well.
```
kind: StorageCluster
spec:
  cloudStorage:
    deviceSpecs:
      - type=gp3,size=500...
    placement:
      nodeAffinity: ...
```
