### ISSUE TITLE
Support volume cloning

### ISSUE THREAD

**Issue by michaelbeaumont** [openebs/mayastor#1718]
**Is your feature request related to a problem? Please describe.**
The CSI driver doesn't support [volume cloning](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/)
so it's not possible to create a PVC from another PVC:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-clone
spec:
  storageClassName: openebs-single-thin-replica
  dataSource:
    name: storage
    kind: PersistentVolumeClaim
```

throws warnings like:

```
failed to provision [...]: CSI driver does not support clone operations: controller CLONE_VOLUME capability is not reported
```

Cloning can be used, for example, with [volsync to backup with clones](https://volsync.readthedocs.io/en/stable/usage/restic/index.html#backup-options)

**Describe the solution you'd like**
Volume cloning supported by the replicated storage CSI driver.

**Describe alternatives you've considered**
Snapshots can be used instead as sources but cloning makes it a little easier to duplicate a volume and doesn't require creating a snapshot just to duplicate a volume.
