### ISSUE TITLE
Diskpools are in "Created" state after 1 node crashed

### ISSUE THREAD

**Issue by veenadong** [openebs/mayastor#1719]
Upgraded from 2.5.1 to 2.7.0.  After the upgrade, 1 node in a 3 node cluster crashed.

1. Mayastor plugin is getting a rest timeout:
    

> core@sc-os-165-node2:~$ kubectl-mayastor get nodes
Failed to list nodes. Error error in request: request timed out

> core@sc-os-165-node3:~$ kubectl mayastor get pools
Failed to list pools. Error error in request: request timed out

2. All diskpools are in "Created" state without any other status:

> core@sc-os-165-node3:~$ kubectl get dsp -A
NAMESPACE   NAME                                         NODE                                    STATE     POOL_STATUS   CAPACITY   USED   AVAILABLE
mayastor    sc-os-165-node1.glcpdev.cloud.hpe.com-disk   sc-os-165-node1.glcpdev.cloud.hpe.com   Created                 0          0      0
mayastor    sc-os-165-node2.glcpdev.cloud.hpe.com-disk   sc-os-165-node2.glcpdev.cloud.hpe.com   Created                 0          0      0
mayastor    sc-os-165-node3.glcpdev.cloud.hpe.com-disk   sc-os-165-node3.glcpdev.cloud.hpe.com   Created                 0          0      0

Currently running nodes:

> core@sc-os-165-node3:~$ kubectl get nodes
NAME                                    STATUS     ROLES    AGE   VERSION
sc-os-165-node1.glcpdev.cloud.hpe.com   NotReady   <none>   27d   v1.28.7
sc-os-165-node2.glcpdev.cloud.hpe.com   Ready      <none>   26d   v1.28.7
sc-os-165-node3.glcpdev.cloud.hpe.com   Ready      <none>   26d   v1.28.7

List of pods running in mayastor namespace:

> mayastor-agent-core-88bc8d8b9-v9k9n             2/2   Running   7 (12h ago)   16h   172.23.155.217   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-agent-ha-node-857bb                    1/1   Running   0             12h   10.245.250.168   sc-os-165-node3.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-agent-ha-node-c5bqw                    1/1   Running   1 (12h ago)   16h   10.245.250.167   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-api-rest-d666fb647-9xbfb               1/1   Running   1 (12h ago)   16h   172.23.155.163   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-csi-controller-799f88d74d-rqcm4        6/6   Running   6 (12h ago)   16h   10.245.250.167   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-csi-node-mmnw8                         2/2   Running   0             12h   10.245.250.168   sc-os-165-node3.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-csi-node-pgkg6                         2/2   Running   2 (12h ago)   16h   10.245.250.167   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-etcd-0                                 0/1   Pending   0             14h   <none>           <none>                                  <none>   <none>
mayastor-etcd-1                                 1/1   Running   5 (12h ago)   16h   172.23.155.140   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-etcd-2                                 1/1   Running   0             12h   172.23.223.112   sc-os-165-node3.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-io-engine-7lmgp                        2/2   Running   0             12h   10.245.250.168   sc-os-165-node3.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-io-engine-vfglv                        2/2   Running   3 (12h ago)   16h   10.245.250.167   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-localpv-provisioner-796cdf4d5b-78w2h   1/1   Running   6 (12h ago)   16h   172.23.155.212   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-nats-0                                 3/3   Running   3 (12h ago)   14h   172.23.155.196   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-nats-1                                 3/3   Running   0             12h   172.23.156.32    sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-nats-2                                 3/3   Running   3 (12h ago)   16h   172.23.155.146   sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>
mayastor-operator-diskpool-5c894c69bf-mjpjq     1/1   Running   0             12h   172.23.156.8     sc-os-165-node2.glcpdev.cloud.hpe.com   <none>   <none>

Versions of all the pods:

> mayastor-agent-core-88bc8d8b9-v9k9n:docker.io/openebs/mayastor-agent-core:v2.7.0, docker.io/openebs/mayastor-agent-ha-cluster:v2.7.0,
mayastor-agent-ha-node-857bb:docker.io/openebs/mayastor-agent-ha-node:v2.7.0,
mayastor-agent-ha-node-c5bqw:docker.io/openebs/mayastor-agent-ha-node:v2.7.0,
mayastor-api-rest-d666fb647-9xbfb:docker.io/openebs/mayastor-api-rest:v2.7.0,
mayastor-csi-controller-799f88d74d-rqcm4:registry.k8s.io/sig-storage/csi-provisioner:v3.5.0, registry.k8s.io/sig-storage/csi-attacher:v4.3.0, registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3, registry.k8s.io/sig-storage/snapshot-controller:v6.3.3, registry.k8s.io/sig-storage/csi-resizer:v1.9.3, docker.io/openebs/mayastor-csi-controller:v2.7.0,
mayastor-csi-node-mmnw8:docker.io/openebs/mayastor-csi-node:v2.7.0, registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0,
mayastor-csi-node-pgkg6:docker.io/openebs/mayastor-csi-node:v2.7.0, registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0,
mayastor-etcd-0:docker.io/bitnami/etcd:3.5.6-debian-11-r10,
mayastor-etcd-1:docker.io/bitnami/etcd:3.5.6-debian-11-r10,
mayastor-etcd-2:docker.io/bitnami/etcd:3.5.6-debian-11-r10,
mayastor-io-engine-7lmgp:docker.io/openebs/mayastor-metrics-exporter-io-engine:v2.7.0, docker.io/openebs/mayastor-io-engine:v2.7.0,
mayastor-io-engine-vfglv:docker.io/openebs/mayastor-metrics-exporter-io-engine:v2.7.0, docker.io/openebs/mayastor-io-engine:v2.7.0,
mayastor-localpv-provisioner-796cdf4d5b-78w2h:openebs/provisioner-localpv:4.1.0,
mayastor-nats-0:nats:2.9.17-alpine, natsio/nats-server-config-reloader:0.10.1, natsio/prometheus-nats-exporter:0.11.0,
mayastor-nats-1:nats:2.9.17-alpine, natsio/nats-server-config-reloader:0.10.1, natsio/prometheus-nats-exporter:0.11.0,
mayastor-nats-2:nats:2.9.17-alpine, natsio/nats-server-config-reloader:0.10.1, natsio/prometheus-nats-exporter:0.11.0,
mayastor-operator-diskpool-5c894c69bf-mjpjq:docker.io/openebs/mayastor-operator-diskpool:v2.7.0

The mayastor plugin didn't capture any of the logs, so I captured using kubectl:

[mayastor.log.tar.gz](https://github.com/user-attachments/files/16604483/mayastor.log.tar.gz)

[mayastor-2024-08-13--16-56-32-UTC.tar.gz](https://github.com/user-attachments/files/16603711/mayastor-2024-08-13--16-56-32-UTC.tar.gz)

**Comment by veenadong** [comment]
Update:
Recovered api-rest by restarting the pod.  This got the diskpools back.  However, io-engine continues to log:
```
[2024-08-13T18:57:26.262907584+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:324] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' connected to subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T18:57:30.982486681+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:344] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' disconnected from subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T18:59:33.849688174+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:324] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' connected to subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T18:59:37.633400695+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:344] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' disconnected from subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T19:00:04.647449691+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:324] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' connected to subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T19:01:42.336838311+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:344] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' disconnected from subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T19:03:45.060224862+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:324] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' connected to subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
[2024-08-13T19:03:48.878250758+00:00  INFO io_engine::subsys::nvmf::subsystem:subsystem.rs:344] Host 'nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com' disconnected from subsystem 'nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' on nexus 'Nexus '3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6' [open]'
```
The pod trying to use this volume:
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  3m49s (x361 over 12h)  kubelet  MountVolume.MountDevice failed for volume "pvc-3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6" : rpc error: code = Internal desc = Failed to stage volume 3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6: failed to mount device /dev/nvme38n1 onto /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/io.openebs.csi-mayastor/c7aaf5d73dfe8640ea445a161e8d9c1cac2fc491de65127619284804b3642647/globalmount: Input/output error (os error 5)
```

Another pod is logging:
```
Events:
  Type     Reason       Age                  From     Message
  ----     ------       ----                 ----     -------
  Warning  FailedMount  11s (x234 over 12h)  kubelet  MountVolume.MountDevice failed for volume "pvc-1b693021-bce1-4490-9916-2a44c3e02a05" : rpc error: code = Unavailable desc = Failed to stage volume 1b693021-bce1-4490-9916-2a44c3e02a05: device attach timeout
```

While the volume is showing as online:
```
core@sc-os-165-node3:~$ kubectl mayastor get volume 1b693021-bce1-4490-9916-2a44c3e02a05
 ID                                    REPLICAS  TARGET-NODE                            ACCESSIBILITY  STATUS  SIZE   THIN-PROVISIONED  ALLOCATED  SNAPSHOTS  SOURCE
 1b693021-bce1-4490-9916-2a44c3e02a05  2         sc-os-165-node3.glcpdev.cloud.hpe.com  nvmf           Online  10GiB  true              1.4GiB     0          <none>
core@sc-os-165-node3:~$ kubectl mayastor get volume 1b693021-bce1-4490-9916-2a44c3e02a05 -o yaml
spec:
  num_replicas: 2
  size: 10737418240
  status: Created
  target:
    node: sc-os-165-node3.glcpdev.cloud.hpe.com
    protocol: nvmf
    frontend_nodes:
    - name: sc-os-165-node3.glcpdev.cloud.hpe.com
      nqn: nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com
  uuid: 1b693021-bce1-4490-9916-2a44c3e02a05
  topology:
    pool_topology: !labelled
      exclusion: {}
      inclusion:
        openebs.io/created-by: operator-diskpool
      affinitykey: []
  policy:
    self_heal: true
  thin: true
  num_snapshots: 0
state:
  target:
    children:
    - state: Online
      uri: bdev:///d89ffaf8-868b-418d-9068-68fd5df377b1?uuid=d89ffaf8-868b-418d-9068-68fd5df377b1
    - state: Online
      uri: nvmf://10.245.250.167:8420/nqn.2019-05.io.openebs:29e303ed-91f3-4888-bd9f-cf11186fe3a7?uuid=29e303ed-91f3-4888-bd9f-cf11186fe3a7
    deviceUri: nvmf://10.245.250.168:8420/nqn.2019-05.io.openebs:1b693021-bce1-4490-9916-2a44c3e02a05?hostnqn=nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com
    node: sc-os-165-node3.glcpdev.cloud.hpe.com
    rebuilds: 0
    protocol: nvmf
    size: 10737418240
    state: Online
    uuid: 6bde92b3-a0e0-4194-a797-0201ec250168
  size: 10737418240
  status: Online
  uuid: 1b693021-bce1-4490-9916-2a44c3e02a05
  replica_topology:
    d89ffaf8-868b-418d-9068-68fd5df377b1:
      node: sc-os-165-node3.glcpdev.cloud.hpe.com
      pool: sc-os-165-node3.glcpdev.cloud.hpe.com-disk
      state: Online
      child-status: Online
      usage:
        capacity: 10737418240
        allocated: 1472200704
        allocated_snapshots: 0
        allocated_all_snapshots: 0
    29e303ed-91f3-4888-bd9f-cf11186fe3a7:
      node: sc-os-165-node2.glcpdev.cloud.hpe.com
      pool: sc-os-165-node2.glcpdev.cloud.hpe.com-disk
      state: Online
      child-status: Online
      usage:
        capacity: 10737418240
        allocated: 1472200704
        allocated_snapshots: 0
        allocated_all_snapshots: 0
  usage:
    capacity: 10737418240
    allocated: 1472200704
    allocated_replica: 1472200704
    allocated_snapshots: 0
    allocated_all_snapshots: 0
    total_allocated: 2944401408
    total_allocated_replicas: 2944401408
    total_allocated_snapshots: 0

```

**Comment by veenadong** [comment]
Noticed errors in csi-node:
```
 2024-08-13T19:54:21.383875Z ERROR csi_node::filesystem_vol: Failed to stage volume 3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6: failed to mount device /dev/nvme38n1 onto /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/io.openebs.csi-mayastor/c7aaf5d73dfe8640ea445a161e8d9c1cac2fc491de65127619284804b3642647/globalmount: Input/output error (os error 5)
    at control-plane/csi-driver/src/bin/node/filesystem_vol.rs:166
```
The volume shows:
```
core@sc-os-165-node3:~$ kubectl mayastor get volume 3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6 -o yaml
spec:
  num_replicas: 2
  size: 32212254720
  status: Created
  target:
    node: sc-os-165-node3.glcpdev.cloud.hpe.com
    protocol: nvmf
    frontend_nodes:
    - name: sc-os-165-node3.glcpdev.cloud.hpe.com
      nqn: nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com
  uuid: 3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6
  topology:
    pool_topology: !labelled
      exclusion: {}
      inclusion:
        openebs.io/created-by: operator-diskpool
      affinitykey: []
  policy:
    self_heal: true
  thin: true
  num_snapshots: 0
state:
  target:
    children:
    - state: Online
      uri: nvmf://10.245.250.167:8420/nqn.2019-05.io.openebs:2855148a-6812-4eed-ae9b-21e2d354bbfd?uuid=2855148a-6812-4eed-ae9b-21e2d354bbfd
    - state: Online
      uri: bdev:///9345ac3a-2c73-47e8-8229-983c0833f8aa?uuid=9345ac3a-2c73-47e8-8229-983c0833f8aa
    deviceUri: nvmf://10.245.250.168:8420/nqn.2019-05.io.openebs:3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6?hostnqn=nqn.2019-05.io.openebs:node-name:sc-os-165-node3.glcpdev.cloud.hpe.com
    node: sc-os-165-node3.glcpdev.cloud.hpe.com
    rebuilds: 0
    protocol: nvmf
    size: 32212254720
    state: Online
    uuid: babd5cf3-d215-46b2-9667-51684b847c22
  size: 32212254720
  status: Online
  uuid: 3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6
  replica_topology:
    9345ac3a-2c73-47e8-8229-983c0833f8aa:
      node: sc-os-165-node3.glcpdev.cloud.hpe.com
      pool: sc-os-165-node3.glcpdev.cloud.hpe.com-disk
      state: Online
      child-status: Online
      usage:
        capacity: 32212254720
        allocated: 947912704
        allocated_snapshots: 0
        allocated_all_snapshots: 0
    2855148a-6812-4eed-ae9b-21e2d354bbfd:
      node: sc-os-165-node2.glcpdev.cloud.hpe.com
      pool: sc-os-165-node2.glcpdev.cloud.hpe.com-disk
      state: Online
      child-status: Online
      usage:
        capacity: 32212254720
        allocated: 947912704
        allocated_snapshots: 0
        allocated_all_snapshots: 0
  usage:
    capacity: 32212254720
    allocated: 947912704
    allocated_replica: 947912704
    allocated_snapshots: 0
    allocated_all_snapshots: 0
    total_allocated: 1895825408
    total_allocated_replicas: 1895825408
    total_allocated_snapshots: 0
```

Using the deviceUri to locate the device on the node:

```
core@sc-os-165-node3:~$ sudo ls -al /dev/disk/by-id/ | grep 38
lrwxrwxrwx 1 root root   13 Aug 12 23:10 nvme-uuid.1c30f7e9-0182-46e7-9f87-f8758389c77b -> ../../nvme2n1
lrwxrwxrwx 1 root root   13 Aug 12 23:21 nvme-uuid.2dc6bf13-18ca-41ec-9b19-2e38bfbd4a89 -> ../../nvme3n1
lrwxrwxrwx 1 root root   14 Aug 12 23:21 nvme-uuid.3b38f55d-20f0-457c-8fde-7febe91174ee -> ../../nvme10n1
lrwxrwxrwx 1 root root   13 Aug 12 23:10 nvme-uuid.838b6fb1-c91f-4689-8a01-fbea59aef50c -> ../../nvme8n1
lrwxrwxrwx 1 root root   13 Aug 12 23:20 nvme-uuid.8efa4538-2a2f-43fc-9670-a44893879756 -> ../../nvme4n1
lrwxrwxrwx 1 root root   14 Aug 12 23:10 nvme-uuid.be874cf3-ef5a-4b2c-a99d-f3838be9cf45 -> ../../nvme12n1
```
Use the nvme-cli to manually attach, but it disappeared after a few min:
```
core@sc-os-165-node3:~$ sudo ls -al /dev/disk/by-id/ | grep 3e
lrwxrwxrwx 1 root root   14 Aug 12 23:20 nvme-uuid.00263e9e-6837-41f0-a77c-c6227394bb47 -> ../../nvme17n1
lrwxrwxrwx 1 root root   14 Aug 13 13:20 nvme-uuid.3e0de6f8-526b-4fe4-b2a4-35f2a471d2a6 -> ../../nvme38n1
lrwxrwxrwx 1 root root   13 Aug 12 23:10 nvme-uuid.4648d3bf-9c75-4969-a87d-6a959f95f3ec -> ../../nvme5n1
lrwxrwxrwx 1 root root   14 Aug 12 23:20 nvme-uuid.df645945-223e-4477-a208-73fe716d47b1 -> ../../nvme31n1
core@sc-os-165-node3:~$ sudo ls -al /dev/disk/by-id/ | grep 3e
lrwxrwxrwx 1 root root   14 Aug 12 23:20 nvme-uuid.00263e9e-6837-41f0-a77c-c6227394bb47 -> ../../nvme17n1
lrwxrwxrwx 1 root root   13 Aug 12 23:10 nvme-uuid.4648d3bf-9c75-4969-a87d-6a959f95f3ec -> ../../nvme5n1
lrwxrwxrwx 1 root root   14 Aug 12 23:20 nvme-uuid.df645945-223e-4477-a208-73fe716d47b1 -> ../../nvme31n1
```
