### ISSUE TITLE
Unable to mount volume with replica backend by NVMe-oF

### ISSUE THREAD

**Issue by Rhodate** [openebs/mayastor#1849]
**Describe the bug**
I have the mayastor helm chart installed to k3s, and two diskpools on two different nodes. When trying to make a pvc that requires 2 replicas it fails to attach to the container with an error from the attachdetach-controller: `AttachVolume.Attach failed for volume "pvc-cd6b30fd-a509-4f37-adcc-4093e08dc7be" : rpc error: code = InvalidArgument desc = error in response: status code '400 Bad Request', content: 'RestJsonError { details: "create_nexus::status: InvalidArgument, message: \"Failed to create child of nexus cd6b30fd-a509-4f37-adcc-4093e08dc7be: Failed to create a BDEV '[2601:197:4400:3f9:41be:847c:5a1f:430d]:8420/nqn.2019-05.io.openebs:2e5ad076-f9dc-4256-854c-17b1a964d871n1'\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Sun, 06 Apr 2025 21:52:39 GMT\", \"content-length\": \"0\"} }", message: "SvcError::GrpcRequestError", kind: InvalidArgument }'`

There are the same errors in the io-engine logs on the node which has a diskpool backed by a raw nvme drive:
[io-engine-nvme.log](https://github.com/user-attachments/files/19623670/io-engine.log)

~~Those errors don't show up on the node with a zfs zvol backed disk pool.~~
Deleted everything and started from scratch. Both have the same issue in the logs now.
[io-engine-zvol.log](https://github.com/user-attachments/files/19626587/io-engine-zvol.log)

The csi-controller pod also has errors that seem related
[csi-controller.log](https://github.com/user-attachments/files/19626739/csi-controller.log)

I have deleted and re-created all of the mayastor/diskpool/pvc resources and it did not fix the issue. I've also confirmed network connectivity from the io-engine to the nvme-of port with telnet.

**To Reproduce**
Running k3s with only ipv6 as the cluster and service cidr, and `--flannel-ipv6-masq`. Otherwise default config.
I deployed using the mayastor helm chart with these values:
```yaml
etcd:                                                                                                                                                                                                              
  affinity: {}                                                                                                                                                                                                     
  replicaCount: 1                                                                                                                                                                                                  
eventing:                                                                                                                                                                                                          
  enabled: false                                                                                                                                                                                                   
obs:                                                                                                                                                                                                               
  callhome:                                                                                                                                                                                                        
    enabled: false
```

<details><summary>DiskPool resources</summary>
<p>

```yaml
Name:         diskpool--dev-disk-by-id-nvme-eui-0025385c2140361b                                                                                                                                                   
Namespace:    mayastor                                                                                                                                                                                             
Labels:       objectset.rio.cattle.io/hash=cf7d519042bb3b97fea5c5e7582892cd3cb4d83f                                                                                                                                
Annotations:  objectset.rio.cattle.io/applied:                                                                                                                                                                     
                H4sIAAAAAAAA/6TSP2vDMBAF8K9Sbrb8N24cQYdCty6dupQOJ+mSqLZ1xqe4hJDvXhQoBEr/QMfTgx/vgU6Ak3+mWTwH0MATBTKSey6WylDEBjLofXCg4cFL/8Q8QAYjRXQYEfQJMA...                                                      
              objectset.rio.cattle.io/id:                                                                                                                                                                          
              objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon                                                                                                                                      
              objectset.rio.cattle.io/owner-name: diskpool--dev-disk-by-id-nvme-eui-0025385c2140361b                                                                                                               
              objectset.rio.cattle.io/owner-namespace: kube-system                                                                                                                                                 
API Version:  openebs.io/v1beta3                                                                                                                                                                                   
Kind:         DiskPool                                                                                                                                                                                             
Metadata:                                                                                                                                                                                                          
  Creation Timestamp:  2025-04-06T17:14:16Z                                                                                                                                                                        
  Finalizers:                                                                                                                                                                                                      
    openebs.io/diskpool-protection                                                                                                                                                                                 
  Generation:        1                                                                                                                                                                                             
  Resource Version:  1475536                                                                                                                                                                                       
  UID:               f9e6e06b-000a-431d-a261-75ac721fb8f5                                                                                                                                                          
Spec:                                                                                                                                                                                                              
  Disks:                                                                                                                                                                                                           
    uring:///dev/disk/by-id/nvme-eui.0025385c2140361b                                                                                                                                                              
  Node:  ophia                                                                                                                                                                                                     
Status:                                                                                                                                                                                                            
  Available:    1912543903744                                                                                                                                                                                      
  Capacity:     1998443249664                                                                                                                                                                                      
  cr_state:     Created                                                                                                                                                                                            
  Encrypted:    false                                                                                                                                                                                              
  pool_status:  Online                                                                                                                                                                                             
  Used:         85899345920                                                                                                                                                                                        
Events:         <none>

---
Name:         diskpool--dev-zvol-zroot-mayastor                                                                                                                                                                    
Namespace:    mayastor                                                                                                                                                                                             
Labels:       objectset.rio.cattle.io/hash=53c965b85cc48ebb368905ab20ecada3e458107a                                                                                                                                
Annotations:  objectset.rio.cattle.io/applied:                                                                                                                                                                     
                H4sIAAAAAAAA/5TPv07DMBAG8FdBN9t1S5qSWmJAYmNhYkEMZ/vUmiS+KOcGtVXeHZmh6sK/8e7T/fTdGXCILzRK5AQWeKBEThaRzbRylLECBW1MASw8RmmfmTtQ0FPGgBnBngFT4o...                                                      
              objectset.rio.cattle.io/id:                                                                                                                                                                          
              objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon                                                                                                                                      
              objectset.rio.cattle.io/owner-name: diskpool--dev-zvol-zroot-mayastor                                                                                                                                
              objectset.rio.cattle.io/owner-namespace: kube-system                                                                                                                                                 
API Version:  openebs.io/v1beta3                                                                                                                                                                                   
Kind:         DiskPool                                                                                                                                                                                             
Metadata:                                                                                                                                                                                                          
  Creation Timestamp:  2025-04-06T17:13:31Z                                                                                                                                                                        
  Finalizers:                                                                                                                                                                                                      
    openebs.io/diskpool-protection                                                                                                                                                                                 
  Generation:        1                                                                                                                                                                                             
  Resource Version:  1475535                                                                                                                                                                                       
  UID:               796c5bb0-3432-48ec-9bc1-dc4f79ffc5cd                                                                                                                                                          
Spec:                                                                                                                                                                                                              
  Disks:                                                                                                                                                                                                           
    uring:///dev/zvol/zroot/mayastor                                                                                                                                                                               
  Node:  chito                                                                                                                                                                                                     
Status:                                                                                                                                                                                                            
  Available:    664981733376                                                                                                                                                                                       
  Capacity:     750881079296                                                                                                                                                                                       
  cr_state:     Created                                                                                                                                                                                            
  Encrypted:    false                                                                                                                                                                                              
  pool_status:  Online                                                                                                                                                                                             
  Used:         85899345920                                                                                                                                                                                        
Events:         <none>
```

</p>
</details> 

<details><summary>PVC/PV resources</summary>
<p>

```yaml
Name:          my-pvc                                                                                                                                                                                              
Namespace:     default                                                                                                                                                                                             
StorageClass:  mayastor-2                                                                                                                                                                                          
Status:        Bound                                                                                                                                                                                               
Volume:        pvc-cd6b30fd-a509-4f37-adcc-4093e08dc7be                                                                                                                                                            
Labels:        <none>                                                                                                                                                                                              
Annotations:   pv.kubernetes.io/bind-completed: yes                                                                                                                                                                
               pv.kubernetes.io/bound-by-controller: yes                                                                                                                                                           
               volume.beta.kubernetes.io/storage-provisioner: io.openebs.csi-mayastor                                                                                                                              
               volume.kubernetes.io/selected-node: ophia                                                                                                                                                           
               volume.kubernetes.io/storage-provisioner: io.openebs.csi-mayastor                                                                                                                                   
Finalizers:    [kubernetes.io/pvc-protection]                                                                                                                                                                      
Capacity:      1Gi                                                                                                                                                                                                 
Access Modes:  RWO                                                                                                                                                                                                 
VolumeMode:    Filesystem                                                                                                                                                                                          
Used By:       my-pod                                                                                                                                                                                              
Events:                                                                                                                                                                                                            
  Type    Reason                 Age                  From                                                                Message                                                                                  
  ----    ------                 ----                 ----                                                                -------                                                                                  
  Normal  WaitForFirstConsumer   3m4s                 persistentvolume-controller                                         waiting for first consumer to be created before binding                                  
  Normal  ExternalProvisioning   3m3s (x2 over 3m3s)  persistentvolume-controller                                         Waiting for a volume to be created either by the external provisioner 'io.openebs.csi-mayastor' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.                                                             
  Normal  Provisioning           3m3s                 io.openebs.csi-mayastor_ophia_e0d6f68c-06a0-4a95-95cb-65e41c9d6ec9  External provisioner is provisioning volume for claim "default/my-pvc"                   
  Normal  ProvisioningSucceeded  3m3s                 io.openebs.csi-mayastor_ophia_e0d6f68c-06a0-4a95-95cb-65e41c9d6ec9  Successfully provisioned volume pvc-cd6b30fd-a509-4f37-adcc-4093e08dc7be

---
Name:              pvc-cd6b30fd-a509-4f37-adcc-4093e08dc7be                                                                                                                                                        
Labels:            <none>                                                                                                                                                                                          
Annotations:       pv.kubernetes.io/provisioned-by: io.openebs.csi-mayastor                                                                                                                                        
                   volume.kubernetes.io/provisioner-deletion-secret-name:                                                                                                                                          
                   volume.kubernetes.io/provisioner-deletion-secret-namespace:                                                                                                                                     
Finalizers:        [kubernetes.io/pv-protection external-attacher/io-openebs-csi-mayastor]                                                                                                                         
StorageClass:      mayastor-2                                                                                                                                                                                      
Status:            Bound                                                                                                                                                                                           
Claim:             default/my-pvc                                                                                                                                                                                  
Reclaim Policy:    Delete                                                                                                                                                                                          
Access Modes:      RWO                                                                                                                                                                                             
VolumeMode:        Filesystem                                                                                                                                                                                      
Capacity:          1Gi                                                                                                                                                                                             
Node Affinity:                                                                                                                                                                                                     
  Required Terms:                                                                                                                                                                                                  
    Term 0:        openebs.io/csi-node in [mayastor]                                                                                                                                                               
Message:                                                                                                                                                                                                           
Source:                                                                                                                                                                                                            
    Type:              CSI (a Container Storage Interface (CSI) volume source)                                                                                                                                     
    Driver:            io.openebs.csi-mayastor                                                                                                                                                                     
    FSType:            ext4                                                                                                                                                                                        
    VolumeHandle:      cd6b30fd-a509-4f37-adcc-4093e08dc7be                                                                                                                                                        
    ReadOnly:          false                                                                                                                                                                                       
    VolumeAttributes:      csi.storage.k8s.io/pv/name=pvc-cd6b30fd-a509-4f37-adcc-4093e08dc7be                                                                                                                     
                           csi.storage.k8s.io/pvc/name=my-pvc                                                                                                                                                      
                           csi.storage.k8s.io/pvc/namespace=default                                                                                                                                                
                           ioTimeout=60                                                                                                                                                                            
                           local=true                                                                                                                                                                              
                           protocol=nvmf                                                                                                                                                                           
                           repl=2                                                                                                                                                                                  
                           storage.kubernetes.io/csiProvisionerIdentity=1743968868958-2015-io.openebs.csi-mayastor                                                                                                 
Events:                <none> 
```

</p>
</details> 

<details><summary>Storage Class</summary>

```yaml
allowVolumeExpansion: true                                                                                                                                                                                         
apiVersion: storage.k8s.io/v1                                                                                                                                                                                      
kind: StorageClass                                                                                                                                                                                                 
metadata:                                                                                                                                                                                                          
  annotations:                                                                                                                                                                                                     
    storageclass.kubernetes.io/is-default-class: "true"                                                                                                                                                            
  creationTimestamp: "2025-04-03T03:36:50Z"                                                                                                                                                                        
  name: mayastor-2                                                                                                                                                                                                 
  resourceVersion: "352227"                                                                                                                                                                                        
  uid: 7693db73-224d-4f04-b2d8-8a8c1623ed79                                                                                                                                                                        
parameters:                                                                                                                                                                                                        
  ioTimeout: "60"                                                                                                                                                                                                  
  local: "true"                                                                                                                                                                                                    
  protocol: nvmf                                                                                                                                                                                                   
  repl: "2"                                                                                                                                                                                                        
provisioner: io.openebs.csi-mayastor                                                                                                                                                                               
reclaimPolicy: Delete                                                                                                                                                                                              
volumeBindingMode: WaitForFirstConsumer
```

<p>



</p>
</details> 

<details><summary>Minimal replication yaml</summary>
<p>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /data
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
```

</p>
</details> 


**Expected behavior**
The volume mounts successfully.

** OS info (please complete the following information):**
 - Distro: NixOS
 - Kernel version: 6.12.21
 - MayaStor revision or container image: 2.9.0-alpha.0 Helm chart
