### ISSUE TITLE
Unable to attach or mount volumes on AWS EKS

### ISSUE THREAD

**Issue by FestivalBobcats** [openebs/Mayastor#306]
**Describe the bug**
This affects both v0.1.0 and v0.2.0. Following the steps outlined in the deploy README, I'm able to create the necessary Mayastor services, but volumes fail to mount with the following error:

```
MountVolume.MountDevice failed for volume "pvc-fb3242d3-4c69-4ddd-a429-21a50e2ade76" : rpc error: code = Internal desc = Failed to mount ext4 fs on /dev/sda with opts "" to /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-fb3242d3-4c69-4ddd-a429-21a50e2ade76/globalmount: No such device (os error 19)
```
```
Unable to attach or mount volumes: unmounted volumes=[ms-volume], unattached volumes=[ms-volume default-token-6qqk4]: timed out waiting for the condition
```

**To Reproduce**
- AWS EKS
- K8S version v1.16.8-eks-e16311
- Amazon Linux 2
- m5ad.large (also tried several other types)
- 1 ephemeral device (not formatted or mounted): /dev/nvme0n1
- iscsi installed / enabled:
```shell
sudo yum install -y iscsi-initiator-utils
sudo systemctl enable iscsid
sudo systemctl start iscsid
echo 512 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
echo 'vm.nr_hugepages = 512' | sudo tee -a /etc/sysctl.conf
sudo service kubelet restart
```
- pool and storage class defined identical to deploy steps in v0.1.0/v0.2.0 (relevant node name and device name in storage pool):
```yaml
NODE_NAME=$(kubectl get nodes -o=jsonpath='{.items[0].metadata.name}')
DISK_NAME='/dev/nvme0n1'

cat <<EOF | kubectl apply -f -
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: pool-on-node-1
  namespace: mayastor
spec:
  node: $NODE_NAME
  disks: ["$DISK_NAME"]
EOF
```
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-iscsi
parameters:
  repl: '1'
  protocol: 'iscsi'
provisioner: io.openebs.csi-mayastor
```
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-iscsi
```
 ```yaml
kind: Pod
apiVersion: v1
metadata:
  name: fio
spec:
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: ms-volume-claim
  containers:
    - name: fio
      image: dmonakhov/alpine-fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ms-volume
```

**Expected behavior**
Expect volume to mount, container to create, Pod to start.

** OS info (please complete the following information):**
 - Distro: Amazon Linux 2
 - Kernel 4.14
 - Mayastor v0.1.0 / v.0.2.0
