### ISSUE TITLE
Can not start test application pod "fio"

### ISSUE THREAD

**Issue by bbroniewski** [openebs/Mayastor#806]
**Description**
Image "https://nixery.dev/shell/fio/tini" can not be pulled in pod "fio". Response from server "404".

**Steps to reproduce**
Apply test pod:
`kubectl apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/fio.yaml`

**Expected behavior**
Image should be pulled normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/11493147/112322678-67974900-8cb1-11eb-9ba9-7593abecace7.png)

**OS info (please complete the following information):**
 - Ubuntu Server 20.04
 - Kernel version: 5.4.0-67-generic
 - MayaStor revision or container image: 0.8

**Additional context**
No

**Comment by jkryl** [comment]
Hi @bbroniewski , you can use arbitrary docker image with fio. The nixery fio image suffers from outages and as we have found out recently, it is not compatible with certain docker versions. If you change image to `dmonakhov/alpine-fio` (for example) in the fio.yaml, you should be fine.

**Comment by bbroniewski** [comment]
Then I need to change commands I guess, because tini is not available?

**Comment by bbroniewski** [comment]
```yaml
kind: Pod
apiVersion: v1
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  name: fio
spec:
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: ms-volume-claim
  containers:
    - name: fio
      image: dmonakhov/alpine-fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ms-volume
```
This is fio yaml file which works.
