### ISSUE TITLE
Pool State Pending When Deployed via helm to ec2 instance running K8s Cluster 

### ISSUE THREAD

**Issue by zeeshanalisyed** [openebs/Mayastor#860]
**Describe the bug**
```mayastornode``` stays in offline state and ```mayastorpool``` stays pending while deploying via a helm chart to ec2 instances  
**To Reproduce**
1. Deploy K8s Cluster via any Cluster Manager tool like ```rancher``` to EC2 instances
2. Assign Required Label to Storage Node
3. Add Secondry Storage Device to Storage Node
4. Restart Storage Node
5. Deploy the helm Chart with the following values in ```values.yaml```
```yaml
mayastorImagesTag: latest
mayastorImagePullPolicy: IfNotPresent
mayastorCpuCount: "1"
mayastorHugePagesGiB: "1"
mayastorImagesRegistry: ""
mayastorPools:
  - node: "openebs1"
    device: "/dev/xvdf"
storageClasses:
  - name: mayastor-iscsi
    replicas: '1'
    protocol: 'iscsi'
    provisioner: io.openebs.csi-mayastor 
  - name: mayastor-nvmf
    replicas: '1'
    protocol: 'nvmf'
    provisioner: io.openebs.csi-mayastor  
moacDebug: false

nats:
  cluster:
    enabled: false
  exporter:
    enabled: false
  logging:
    debug: true
    trace: true

```
**Expected behavior**

I expected ```mayastornode``` to be in online state, I tested the same values helm chart on local baremetal k8s cluster having extra storage devices attached it is working perfectly it only gives problem in ec2 instance.

**Screenshots**
### State of the Pool and Node
![debug-att](https://user-images.githubusercontent.com/8758274/116386444-d294ec00-a82a-11eb-8b77-6d18a7165b40.png)
### All
![all](https://user-images.githubusercontent.com/8758274/116386505-e6d8e900-a82a-11eb-9cee-c6b82bcc762c.png)

** OS info (please complete the following information):Ubuntu 16.04.4 LTS
 - Distro: Ubuntu
 - Kernel version: Linux 4.4.0-1128-aws
 - MayaStor revision or container image: latest

**Additional context**
Cloud Providor: Amazon Web Services
Instance: EC2
Cluster Size: 5 Nodes
Storage Node: 1
I am new to Mayastor Maybe I am missing something
